---
dn:
  org: Allevac 
  state: Maryland
  city: Baltimore
  country: US

ku:
  - digSignature
  - keyEncipher

eku:
  - serverAuth
  - clientAuth

rsa:
  ku:
    - digSignature
    - keyEncipher
  eku:
    - serverAuth
    - clientAuth
  san:
    upn: example.com        # Domain to be combined with CN